# “Git push -f” или после нас хоть потоп

# 0. Где мы сейчас?
<img src="https://upload.wikimedia.org/wikipedia/commons/thumb/3/38/Jupyter_logo.svg/1200px-Jupyter_logo.svg.png" width="150">

[Jupyter Notebook](https://jupyter.org/) - интерактивная среда для запуска программного кода в браузере. Удобный инструмент для анализа данных, который используется многими специалистами по data science. Позволяет выполнять отдельные ячейки с кодом, а не всю программу сразу, что очень удобно при знакомстве с данными.

# 1. Python
> Python - это свободный интерпретируемый объектно-ориентированный расширяемый встраиваемый язык программирования очень высокого уровня

>*(Г.Россум, Ф.Л.Дж.Дрейк, Д.С.Откидач "Язык программирования Python").*

А если без цитат, то питон - это просто очень крутой язык, созданный в 1991 году [Великодушным пожизненным диктатором](https://ru.wikipedia.org/wiki/%D0%92%D0%B5%D0%BB%D0%B8%D0%BA%D0%BE%D0%B4%D1%83%D1%88%D0%BD%D1%8B%D0%B9_%D0%BF%D0%BE%D0%B6%D0%B8%D0%B7%D0%BD%D0%B5%D0%BD%D0%BD%D1%8B%D0%B9_%D0%B4%D0%B8%D0%BA%D1%82%D0%B0%D1%82%D0%BE%D1%80) Гвидо ван Россумом и названный в честь любимого им шоу [Monty Python's Flying Circus](https://en.wikipedia.org/wiki/Monty_Python%27s_Flying_Circus)

<img src="https://advancelocal-adapter-image-uploads.s3.amazonaws.com/image.oregonlive.com/home/olive-media/width2048/img/tv/photo/2018/10/10/montycastjpg-7ef393e2355a42aa.jpg" width="300">

# 2. Anaconda

[Сборка Anaconda](https://www.anaconda.com/products/individual) включает очень много полезных библиотек для анализа данных.

Среди наиболее популярных библиотек:
 - <a href="http://numpy.org">Numpy</a> - это один из основных пакетов для математических вычислений. Он содержит средства для работы с многомерными массивами и высокоуровневыми математическими функциями
 - <a href="https://www.scipy.org/">SciPy</a> - научные вычисления. Методы оптимизации, интегрирования, модули обработки сигналов и изображений, статистика, линейная алгебра, сплайны, кластеризация и многое другое
 -  <a href="http://pandas.pydata.org/">Pandas</a> - основная библиотека для обработки и анализа данных. Предназначена для данных разной природы - матричных, панельных данных, временных рядов. Претендует на звание самого мощного и гибкого средства для анализа данных с открытым исходным кодом
 - <a href="http://scikit-learn.org/stable/">Scikit-learn</a> - реализация очень многих методов машинного обучения с отличной документацией.
 - <a href="http://http://matplotlib.org/">matplotlib</a> - хорошая библиотека для визуализации данных

 С этими библиотеками вы будете знакомится дальше на курсе, а пока давайте попрактикуемся в решении базовых задач на  чистом Python.

# 3. Задачки

## Задача 1
$N$ хоббитов делят $K$ кусков эльфийского хлеба поровну, не делящийся нацело остаток остается в корзинке у Сэма. Напишите функцию, которая принимает на вход параметры $N$ и $K$ и возвращает два числа: $x$ - cколько кусков эльфиского хлеба достанется каждому хоббиту, и $y$ - сколько кусков остаётся в корзинке.

In [2]:
def share_bread(N, K):
    if N > K:
        raise ValueError("Слишком мало кусков!")

    x = K // N
    y = K % N
    return x, y

assert share_bread(N=3, K=14) == (4, 2)

## Задача 2

В копях Мории хоббиты нашли стену, на которой высечены разные натуральные числа. Согласно древним сказаниям, это даты сражений. Хоббиты знают, что сражения происходили только по високосным годам. Помогите хоббитам определить, является ли год с данным числом датой великого сражения. Если это так, то верните строку "YOU SHALL PASS", иначе верните "YOU SHALL NOT PASS". Напомним, что в соответствии с хоббитским календарем, год является високосным, если его номер кратен 4, но не кратен 100, а также если он кратен 400.

In [11]:
def leap_year(year):
    if not isinstance(year, int) or year < 1:
        raise ValueError("Неверно введен год!")

    if (year % 4 == 0 and year % 100 != 0) or (year % 400 == 0):
        return "YOU SHALL PASS"
    else:
        return "YOU SHALL NOT PASS"

assert leap_year(5) == 'YOU SHALL NOT PASS'
assert leap_year(2026) == 'YOU SHALL NOT PASS'
assert leap_year(2028) == 'YOU SHALL PASS'

## Задача 3
<img src="http://i0.kym-cdn.com/photos/images/original/001/187/255/5e9.gif" width=300>


Для могущественного магического ритуала Гендальфу необходимо быстро подсчитывать площадь своего амулета, который умеет менять размеры. Известно, что амулет имеет форму треугольника и Гендальф знает длину каждой из сторон. Напишите функцию, которая считает площадь амулета по трем сторонам.  

**Подсказка:** используйте формулу Герона
$$ S = \sqrt{p(p-a)(p-b)(p-c)} $$
$$ p = \frac{a + b + c}{2}$$


In [12]:
def amulet_area(a, b, c):
    if a <= 0 or b <= 0 or c <= 0 or a + b <= c or a + c <= b or b + c <= a:
        raise ValueError("Неверно заданы стороны!")

    p = (a + b + c) / 2
    s = (p * (p - a) * (p - b) * (p - c)) ** 0.5
    return s

assert amulet_area(3, 4, 5) == 6

## Задача 4

Хоббиты собираются пешком идти до Мордора и им нужно подсчитать расстояние, которое им предстоит пройти. Хоббиты смогли вспомнить сразу несколько метрик расстояния: евклидово, манхэттена и косинусное, так что ваша задача - написать функцию под каждую из них. Важное условие - используйте только базовые функции для решения.


* Евклидово расстояние
$$ d(a, b) = \sqrt{\sum_i (a_i - b_i)^2} $$
* Расстояние Манхэттена
$$ d(a, b) = \sum_i |a_i - b_i| $$
* Косинусное расстояние
$$ d(a, b) = 1 - \frac{a^\top b}{||a||_2\cdot||b||_2}$$

In [27]:
def cal_euclidean(a, b):
    if len(a) == 0 or len(b) == 0:
        raise ValueError("Неверно заданы входные данные!")

    sum_squared = 0
    for i in range(len(a)):
        diff = a[i] - b[i]
        sum_squared += diff * diff
    distance = sum_squared ** 0.5
    return distance

def cal_manhattan(a, b):
    if len(a) == 0 or len(b) == 0:
        raise ValueError("Неверно заданы входные данные!")
    distance = 0
    for i in range(len(a)):
        distance += abs(a[i] - b[i])
    return distance

def cal_cosine(a, b):
    if len(a) == 0 or len(b) == 0:
         raise ValueError("Неверно заданы входные данные!")

    dot_product = 0
    for i in range(len(a)):
        dot_product += a[i] * b[i]

    norm_a = 0
    for i in range(len(a)):
        norm_a += a[i] * a[i]
    norm_a = norm_a ** 0.5

    norm_b = 0
    for i in range(len(b)):
        norm_b += b[i] * b[i]
    norm_b = norm_b ** 0.5

    if norm_a == 0 or norm_b == 0:
        return 1.0

    cosine_similarity = dot_product / (norm_a * norm_b)
    distance = 1 - cosine_similarity
    return distance

In [28]:
import numpy as np


a = np.random.randint(-10, 10, size=10)
b = np.random.randint(-10, 10, size=10)

print("Вектор a:", a)
print("Вектор b:", b)
print("Евклидово расстояние:", cal_euclidean(a, b))
print("Манхэттен расстояние:", cal_manhattan(a, b))
print("Косинусное расстояние:", cal_cosine(a, b))

Вектор a: [ 4 -9 -2 -3 -2 -7 -1 -5 -1  8]
Вектор b: [-1 -4 -8 -6 -5  7 -3  4 -4  9]
Евклидово расстояние: 19.87460691435179
Манхэттен расстояние: 51
Косинусное расстояние: 0.6949932686218091


## Задача 5* (бонусное неоцениваемое задание)

**Замечание:** Поскольку библиотеку numpy мы будем подробно разбирать дальше, то это задание является бонусным, его выполнение необязательно для сдачи ДЗ и не влияет на итоговый балл. Как вариант, можете вернуться к нему после прохождения numpy ;)



Создайте случайный array (`np.random.rand()`) длинной 100. Преобразуйте его так, чтобы
* Максимальный элемент(ы) был равен 1
* Минимальный элемент(ы) был равен 0
* Остальные элементы в интервале от 0 до 1 остаются прежними

In [29]:
import numpy as np

my_array = np.random.rand(100)
my_array = (my_array - np.min(my_array)) / (np.max(my_array) - np.min(my_array))

print(np.max(my_array), np.min(my_array))
print(my_array)

1.0 0.0
[0.11322595 0.35086628 0.9354443  0.36928557 0.99798457 0.94006289
 0.70355278 0.65509103 0.91202259 0.2116031  0.20452651 0.79487777
 0.91534787 0.00605242 0.64854914 0.83516219 0.82706702 0.3541288
 0.07362696 0.42870267 0.82587089 0.43750631 0.54012749 0.68582065
 0.9213954  0.70882112 0.93318706 0.57145384 0.5221282  0.84521352
 0.83112512 0.75231159 0.34487019 0.21756389 0.85875688 0.2912033
 0.29894276 0.53120946 0.48138738 0.35692959 0.51330935 0.19243862
 0.69888952 0.31885659 0.11138882 0.76415309 1.         0.20070301
 0.97498364 0.90755196 0.25138546 0.93052329 0.83358162 0.29309403
 0.10873731 0.46752022 0.0274977  0.9170038  0.36791098 0.04633468
 0.01866839 0.75180349 0.41624818 0.58861673 0.25549708 0.99533472
 0.28506433 0.8807914  0.62655621 0.22454089 0.70740124 0.20436016
 0.51896137 0.26763375 0.02849709 0.55426635 0.1804651  0.91177584
 0.69900611 0.79926472 0.38181189 0.89545572 0.01269976 0.65638698
 0.38964725 0.23565446 0.14600277 0.26911546 0.78520021 

Создайте array размером $5 \times 6$ с целыми числами в интервале [0,50]. Напечатайте колонку, которая содержит максимальный элемент полученной матрицы

In [31]:
import numpy as np

my_array = np.random.randint(0, 51, size=(5, 5))

# Находим индекс максимального элемента
max_idx = np.argmax(my_array)
# Определяем колонку (столбец) этого элемента
max_col_idx = max_idx % my_array.shape[1]
# Выбираем всю колонку
selected_column = my_array[:, max_col_idx]

print('Shape: ', my_array.shape)
print('Array')
print(my_array)
print('Max element:')
print(selected_column)

Shape:  (5, 5)
Array
[[31 25 14 35  2]
 [35 20 25 21 14]
 [37 19 46 43 48]
 [17  6 14 29 12]
 [25 11 35 36  4]]
Max element:
[ 2 14 48 12  4]


Напишите функцию, которая принимает на вход матрицу (array) X и возвращает все её уникальные строки в виде новой матрицы.

In [40]:
def get_unique_rows(X):
    return np.unique(X, axis=0)

In [42]:
X = np.random.randint(4, 6, size=(10,3))
print('Исходная')
print(X)

Исходная
[[5 4 4]
 [4 4 4]
 [5 5 5]
 [4 5 5]
 [5 4 5]
 [5 5 5]
 [5 4 4]
 [5 4 4]
 [4 5 5]
 [5 4 4]]


In [43]:
X = get_unique_rows(X)
print('Новая')
print(X)

Новая
[[4 4 4]
 [4 5 5]
 [5 4 4]
 [5 4 5]
 [5 5 5]]
